### ISSUE TITLE
Found a proof, no email

### ISSUE THREAD

**Issue by Gregwolf3030** [martomi/chiadog#182] opened 2021-05-24 18:01 UTC
Latest versions of everything (linux, PIP, chia and chiadog). It is a remote harvester monitoring a local (local to the harvester) farm. I noticed a new block reward in my chia GUI but had not received a chiadog email notification. I logged into the remote harvester and see the "Found a proof!" message in the chiadog window. But no email came through. I do receive the daily stats email. I checked the config file and under notifier -> email, both daily_stats and wallet_events are set to true. Is there a place to look for error messages? Maybe a log file somewhere? I couldn't find one.

**Comment by martomi** [comment] 2021-05-24 18:36
The XCH notifications work only in the following scenario: 

> Running full node + harvester + wallet on the same machine and receiving rewards on that same wallet. 

These notifications are just a bonus on top of critical alerts in monitoring your harvesters, so resolving that won't be a priority from my side but contributions are welcome.

Closing this as duplicate of #167

**Closed by martomi** 2021-05-24 18:36 UTC

**Comment by Gregwolf3030** [comment] 2021-05-24 18:46
I appreciate the information, but I searched all of the open and closed issues before I opened the issue and did not find this as an existing issue. Not fair classifying it as a duplicate. If it is a duplicate, then link to the resolved issue showing me the duplicate.

**Comment by martomi** [comment] 2021-05-24 18:48
I've linked it above #167 

Not blaming that you opened a duplicate, I'm just consolidating few closely related issues into the same one.
