### ISSUE TITLE
Chiadog may be reporting 1.75 XCH winnings incorrectly for NFT plot wins

### ISSUE THREAD

**Issue by brianwfreeman** [martomi/chiadog#301] opened 2021-10-12 13:40 UTC
**Describe the bug**

At 4:20AM today I received a Chiadog alert that I won a block - 1.75 and 0.25 to hit my wallet.  However my Chia wallet only reflects receiving the 0.25. See below:

Wallet receive address: xch1ynjcxy3t6gw5xlqhwxl8etwf28v0kvwsmhtjm9sa2f5fullmcajszmhyne

I suspect Chiadog may have reported a win on an NFT plot and the 1.75 went to the pool, not me.

**Environment:**
 - OS: 
 - Python version:
 - PIP version:
 - Chia version:
 - Chiadog version: 
 - Harvester: remote OR loc
![IMG_3532](https://user-images.githubusercontent.com/17950149/136966865-b538dcac-6cbb-402d-b340-77bcde3d84f6.PNG)
al

**Comment by martomi** [comment] 2021-10-12 21:20
Thanks for the report, I'll close this one as it's a duplicate of https://github.com/martomi/chiadog/issues/286

**Closed as completed by martomi** 2021-10-12 21:20 UTC
Labels: duplicate
