### ISSUE TITLE
False-failure of harvester detected

### ISSUE THREAD

**Issue by fiveangle** [martomi/chiadog#92] opened 2021-05-07 06:56 UTC
chiadog notified me of  "harvester appears to be offline" t 401s, 701s, then 1001s.  However, the GUI showed the remote harvester lookups scrolling through as expected and tailing the debug logs showed the same.  I quit and restarted chiadog without any other changes, and it started as expected without any errors or warnings and began functioning as expected again.

I know that the Windows implementation is relatively new, so how should I prepare to capture additional detail assuming a similar problem will occur again ?

Thanks again for such an awesome aid for us little farmers ! :) 

 - OS: Windos 10 Pro AMD64 (latest patchlevel)
 - Python version: 3.9.5:0a7dcbd 64-bit for Windows
 - PIP version: 21.1.1
 - Chia version: 1.1.4 for Windows (+1.1.4 for remote harvesters running on Ubuntu 21.04)
 - chiadog version: 592dcc900990191c2385c701664787dea59c3628

**Comment by pieterhelsen** [comment] 2021-05-07 07:48
Thanks for the bug report!
This is presumably a duplicate of #72. A solution is in the works!

**Closed by pieterhelsen** 2021-05-07 07:48 UTC

**Comment by fiveangle** [comment] 2021-05-07 08:48
Sorry I missed not seeing #72.  Thx !

**Comment by fiveangle** [comment] 2021-05-07 09:07
![image](https://user-images.githubusercontent.com/2219447/117426450-c3700700-aed8-11eb-81b0-a9668c585796.png)

![image](https://user-images.githubusercontent.com/2219447/117426644-f7e3c300-aed8-11eb-95bf-e99fb2c709e0.png)
